network:
  version: 2
  renderer: networkd
  ethernets:
    enp5s0f0:
      dhcp6: false
      match:
        name: enp5s0f0
      addresses:
      - 2607:5300:0203:7712::/64
      gateway6: 2607:5300:0203:77FF:FF:FF:FF:FF
      nameservers:
        addresses:
        - 2606:4700:4700::1112
        - 2606:4700:4700::1002
      routes:
      - to: 2607:5300:0203:77FF:FF:FF:FF:FF
        scope: link
    enp5s0f1:
      addresses:
      - 51.222.70.225/32
      gateway4: 51.222.70.254 
      routes:
      - to: 51.222.70.254
        scope: link
      nameservers:
        addresses:
        - 1.1.1.2
        - 1.0.0.2
  vlans:
    vlan99:
      id: 99
      link: enp5s0f1
      addresses: 
      - 192.168.0.2/16