network:
  version: 2
  renderer: networkd
  ethernets:
    eno4:
      match:
        macaddress: 0c:c4:7a:c5:a7:31
      gateway4: 51.222.70.254
      addresses:
      - 51.222.70.227/32
      routes:
      - to: 51.222.70.254
        scope: link
